### ISSUE TITLE
No Label printing possible in 1.9.2.2

### ISSUE THREAD

**Issue by Webmasterei** [mvgucht/dpd-shipping-magento#5]
Hi,
I installed & configured the module. 

When I try to genereate labels and complete I always get the error:

"Die Bestellung mit der ID 100000007 ist nicht versandbereit oder wurde kürzlich versendet."

Is this a version problem? In Magentoconnect it says it's only up to 1.8.1.

**Comment by mvgucht** [comment]
Hey,

please find the 'official' extensions here: https://github.com/DPDBeNeLux/magento-DPD_Shipping

don't use magento connect to install the extension in magento 1.9, it sometimes makes fiels into folders ... (and I don't know why). Remove all the folders that the extension added by installing it via magento connect en upload the extension from github to your root folder.

the error that you forwarded is linked to the fact that you 'shipped' the order by clicking 'ship' in the order. you can't ship it before generating the labels.

please find the tutorials here:
http://www.youtube.com/playlist?list=PLjsdIPkS7GvT0wHa6CHbXs4RLGdBm7Bcx

**Comment by Webmasterei** [comment]
Thanks! After 3 hours of testing and wondering and trying everything from magentoconnect. 
I think for the rest of your customers it'd be superawesome to update the manual here too: http://www.dpd.com/lu_de/media/files/magento_dpd_shipping_module_1_1_0 and have some claryfing words on the magentoconnect extensions.... also you should inform DPD customer service as well as they "officially" recommending magentoconnect...
